local vim_g = vim.g
local opt = vim.opt

--disable_distribution_plugins
vim_g.loaded = 1
vim_g.loaded_netrwPlugin = 1
vim_g.loaded_gzip = 1
vim_g.loaded_tar = 1
vim_g.loaded_tarPlugin = 1
vim_g.loaded_zip = 1
vim_g.loaded_zipPlugin = 1
vim_g.loaded_getscript = 1
vim_g.loaded_getscriptPlugin = 1
vim_g.loaded_vimball = 1
vim_g.loaded_vimballPlugin = 1
vim_g.loaded_matchit = 1
vim_g.loaded_matchparen = 1
vim_g.loaded_2html_plugin = 1
vim_g.loaded_logiPat = 1
vim_g.loaded_rrhelper = 1
vim_g.loaded_netrw = 1
vim_g.loaded_netrwPlugin = 1
vim_g.loaded_netrwSettings = 1
vim_g.loaded_netrwFileHandlers = 1


opt.termguicolors = true
opt.mouse = 'nv'
opt.errorbells = true
opt.visualbell = true
opt.hidden = true
opt.fileformats = 'unix,mac,dos'
opt.magic = true
opt.virtualedit = 'block'
opt.encoding = 'utf-8'
opt.viewoptions = 'folds,cursor,curdir,slash,unix'
opt.sessionoptions = 'curdir,help,tabpages,winsize'
opt.clipboard = 'unnamedplus'
opt.wildignorecase = true
opt.wildignore =
  '.git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**'
opt.backup = false
opt.writebackup = false
opt.swapfile = false
opt.history = 2000
opt.shada = "!,'300,<50,@100,s10,h"
opt.backupskip = '/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*,*/shm/*,/private/var/*,.vault.vim'
opt.smarttab = true
opt.shiftround = true
opt.timeout = true
opt.ttimeout = true
opt.timeoutlen = 500
opt.ttimeoutlen = 10
opt.updatetime = 100
opt.redrawtime = 1500
opt.ignorecase = true
opt.smartcase = true
opt.infercase = true
opt.incsearch = true
opt.wrapscan = true
opt.complete = '.,w,b,k'
opt.inccommand = 'nosplit'
opt.grepformat = '%f:%l:%c:%m'
opt.grepprg = 'rg --hidden --vimgrep --smart-case --'
opt.breakat = [[\ \	;:,!?]]
opt.startofline = false
opt.whichwrap = 'h,l,<,>,[,],~'
opt.splitbelow = true
opt.splitright = true
opt.switchbuf = 'useopen'
opt.backspace = 'indent,eol,start'
opt.diffopt = 'filler,iwhite,internal,algorithm:patience'
opt.completeopt = 'menu,menuone,noselect'
opt.jumpoptions = 'stack'
opt.showmode = false
opt.shortmess = 'aoOTIcF'
opt.scrolloff = 2
opt.sidescrolloff = 5
opt.foldlevelstart = 99
opt.ruler = false
opt.cursorline = true
opt.cursorcolumn = true
opt.list = true
opt.showtabline = 0
opt.winwidth = 30
opt.winminwidth = 10
opt.pumheight = 15
opt.helpheight = 12
opt.previewheight = 12
opt.showcmd = false
-- just for nightly
opt.cmdwinheight = 5
opt.equalalways = false
opt.laststatus = 3
opt.display = 'lastline'
opt.showbreak = '↳  '
opt.listchars = 'tab:»·,nbsp:+,trail:·,extends:→,precedes:←'
opt.pumblend = 10
opt.winblend = 10

opt.undofile = true
opt.synmaxcol = 2500
opt.formatoptions = '1jcroql'
opt.textwidth = 80
opt.expandtab = true
opt.autoindent = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.softtabstop = -1
opt.breakindentopt = 'shift:2,min:20'
opt.wrap = false
opt.linebreak = true
opt.number = true
opt.relativenumber = true
opt.colorcolumn = '100'
opt.foldenable = true
opt.signcolumn = 'yes'
-- opt.conceallevel = 2
-- opt.concealcursor = 'niv'
